version: '3'
services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messages-app
    ports:
    - "8000:8000"
    depends_on:
      - database
    restart: always
    environment:
      DEBUG: "true"

  database:
    image: postgres:13
    container_name: messages-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres